In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
sent=['the glass of milk',
      'the glass of water',
      'rushil is gay',
      'i am gay too',
      'raj and ibrahim are gay boys',
      'soham is female']

In [4]:
sent

['the glass of milk',
 'the glass of water',
 'rushil is gay',
 'i am gay too',
 'raj and ibrahim are gay boys',
 'soham is female']

In [5]:
voc_size = 10000

In [7]:
one_hot_repr = [ one_hot(words , voc_size)for words in sent]
one_hot_repr

[[845, 7496, 9351, 2696],
 [845, 7496, 9351, 1125],
 [1447, 3340, 920],
 [2193, 2456, 920, 4508],
 [4097, 1905, 8466, 9863, 920, 1119],
 [9450, 3340, 9116]]

In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  845 7496 9351 2696]
 [   0    0    0    0  845 7496 9351 1125]
 [   0    0    0    0    0 1447 3340  920]
 [   0    0    0    0 2193 2456  920 4508]
 [   0    0 4097 1905 8466 9863  920 1119]
 [   0    0    0    0    0 9450 3340 9116]]


In [11]:
dim = 10

In [12]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam', 'mse')

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [15]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 223ms/step


array([[[-2.65350472e-02, -1.34430528e-02,  4.34280075e-02,
         -2.70407926e-02, -3.24517712e-02, -3.39525566e-02,
          2.45599858e-02,  2.25714557e-02, -6.13880157e-03,
         -1.63941383e-02],
        [-2.65350472e-02, -1.34430528e-02,  4.34280075e-02,
         -2.70407926e-02, -3.24517712e-02, -3.39525566e-02,
          2.45599858e-02,  2.25714557e-02, -6.13880157e-03,
         -1.63941383e-02],
        [-2.65350472e-02, -1.34430528e-02,  4.34280075e-02,
         -2.70407926e-02, -3.24517712e-02, -3.39525566e-02,
          2.45599858e-02,  2.25714557e-02, -6.13880157e-03,
         -1.63941383e-02],
        [-2.65350472e-02, -1.34430528e-02,  4.34280075e-02,
         -2.70407926e-02, -3.24517712e-02, -3.39525566e-02,
          2.45599858e-02,  2.25714557e-02, -6.13880157e-03,
         -1.63941383e-02],
        [ 4.14880998e-02,  3.21536325e-02, -2.44251378e-02,
         -4.95465063e-02,  8.33768770e-03,  2.56424807e-02,
         -3.74686830e-02, -4.49760556e-02,  3.254405